### ISSUE TITLE
support logstore sync feature

### ISSUE THREAD

**Issue by wjo1212** [aliyun/aliyun-log-cli#37]
1. copy logs from one logstore to another one
2. support cross region
3. support copy with condition (search filter)
4. support continues copy (via consumer group)
5. support real-time copy (keep copying new incoming data)

**Comment by wjo1212** [comment]
support 1, 2 now

**Comment by caryyu** [comment]
@wjo1212 Any tutorials that we'd be able to read?

**Comment by wjo1212** [comment]
@caryyu now bullet 1, 2 are supported. 
 
https://yq.aliyun.com/articles/636836
https://aliyun-log-cli.readthedocs.io/en/latest/tutorials/tutorial_copy_data.html

for item 3-5 it's traced in another Issue #47 , coming soon

**Comment by wjo1212** [comment]
supported by aliyun-log-python-sdk 0.6.36
